[project]
name = "chromatin3d"
version = "0.1.0"
description = "Chromatin 3D Structure Prediction with Physics-Informed Neural Networks (PINNs)"
authors = [
    {name = "Michał Legczylin",email = "legczylin.michal@gmail.com"},
    {name = "Sevastianos Korsak"},
    {name = "Dariusz Plewczyński"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "chromatin3d", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
