[project]
name = "chromatin3d"
version = "0.1.0"
description = "Chromatin 3D Structure Prediction with Physics-Informed Neural Networks (PINNs)"
authors = [
    {name = "Michał Legczylin",email = "legczylin.michal@gmail.com"},
    {name = "Sevastianos Korsak"},
    {name = "Dariusz Plewczyński"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "torch (>=2.14.1,<3.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "tqdm (>=4.70.1,<5.0.0)",
    "torchmetrics (>=1.9.0,<2.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "scipy (>=1.18.1,<2.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
]

[tool.poetry]
packages = [{include = "chromatin3d", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.10,<0.17.0)",
    "mypy (>=2.4.0,<3.0.0)",
    "notebook (>=7.6.3,<8.0.0)"
]

[tool.ruff]
line-length = 200
indent-width = 4

[tool.ruff.lint]
#ignore = ["RUF012"]
isort.split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = true
indent-style = "space"